services:
    sms_main.admin.phone:
        class: SMS\MainBundle\Admin\PhoneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Phone", label: "Phone" }
        arguments:
            - ~
            - SMS\MainBundle\Entity\Phone
            - ~
        calls:
            - [ setTranslationDomain, [SMSMainBundle]]
    sms_main.admin.computer:
        class: SMS\MainBundle\Admin\ComputerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Computer", label: "Computer" }
        arguments:
            - ~
            - SMS\MainBundle\Entity\Computer
            - ~
        calls:
            - [ setTranslationDomain, [SMSMainBundle]]
