sms_main_index:
    path:     /
    defaults: { _controller: SMSMainBundle:Default:index }
sms_main_compte:
    path:     /account
    defaults: { _controller: SMSMainBundle:Default:account }
sms_main_services:
    path:     /services
    defaults: { _controller: SMSMainBundle:Default:services }
sms_main_about:
    path:     /about
    defaults: { _controller: SMSMainBundle:Default:about }
sms_main_contact:
    path:     /contact
    defaults: { _controller: SMSMainBundle:Default:contact }
sms_main_news:
    path:     /blog
    defaults: { _controller: SMSMainBundle:Blog:blog }
sms_main_article:
    path:     /blog/{id}
    defaults: { _controller: SMSMainBundle:Blog:article }
