parameters:
#    sms_main.example.class: SMS\MainBundle\Example

services:
#    sms_main.example:
#        class: %sms_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sms_main.menu_builder:
        class: SMS\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    sms_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sms_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu