<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use SMS\MainBundle\Entity\Phone;
use SMS\MainBundle\Entity\Computer;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="SMS\MainBundle\Entity\Phone", mappedBy="user")
     */
    protected $phones;

    /**²
     * @var Collection
     * @ORM\OneToMany(targetEntity="SMS\MainBundle\Entity\Computer", mappedBy="user")
     */
    protected $computers;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
                parent::__construct();

        $this->phones = new ArrayCollection();
        $this->computers = new ArrayCollection();
    }

   
    /**
     * Add phone
     *
     * @param \SMS\MainBundle\Entity\Phone $phone
     * @return User
     */
    public function addPhone(\SMS\MainBundle\Entity\Phone $phone)
    {
        $this->phones[] = $phone;

        return $this;
    }

    /**
     * Remove phone
     *
     * @param \SMS\MainBundle\Entity\Phone $phone
     */
    public function removePhone(\SMS\MainBundle\Entity\Phone $phone)
    {
        $this->phones->removeElement($phone);
    }

    /**
     * Get phones
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPhones()
    {
        return $this->phones;
    }
    /**
     * Add computer
     *
     * @param \SMS\MainBundle\Entity\Phone $computer
     * @return User
     */
    public function addComputer(\SMS\MainBundle\Entity\Computer $computer)
    {
        $this->computers[] = $computer;

        return $this;
    }

    /**
     * Remove computer
     *
     * @param \SMS\MainBundle\Entity\Phone $computer
     */
    public function removeComputer(\SMS\MainBundle\Entity\Computer $computer)
    {
        $this->computers->removeElement($computer);
    }

    /**
     * Get phones
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComputers()
    {
        return $this->computers;
    }
}
